title: Ananya Gupta
logo: "/logo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/ananya-gupta-4ab9671b4">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
